---
- name: Update all system packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Ensure basic tools are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - unzip

- name: Set timezone to UTC
  timezone:
    name: UTC
